// Dados do jogo: craques, times e selecoes
const CRAQUES = [
  { id: 'cr7', nome: 'Cristiano Ronaldo', apelido: 'CR7', pais: 'Portugal', time: 'Al Nassr', pos: 'ATA', overall: 93, penalti: 94, avatar: '🐐', cor: '#c0392b' },
  { id: 'messi', nome: 'Lionel Messi', apelido: 'Messi', pais: 'Argentina', time: 'Inter Miami', pos: 'ATA', overall: 93, penalti: 92, avatar: '🐐', cor: '#2980b9' },
  { id: 'neymar', nome: 'Neymar Jr', apelido: 'Neymar', pais: 'Brasil', time: 'Santos', pos: 'ATA', overall: 91, penalti: 90, avatar: '🪄', cor: '#27ae60' },
  { id: 'haaland', nome: 'Erling Haaland', apelido: 'Haaland', pais: 'Noruega', time: 'Man City', pos: 'ATA', overall: 92, penalti: 90, avatar: '🤖', cor: '#6c3483' },
  { id: 'yamal', nome: 'Lamine Yamal', apelido: 'Yamal', pais: 'Espanha', time: 'Barça', pos: 'ATA', overall: 90, penalti: 86, avatar: '🌟', cor: '#8e44ad' },
  { id: 'lewa', nome: 'Robert Lewandowski', apelido: 'Lewa', pais: 'Polônia', time: 'Barça', pos: 'ATA', overall: 91, penalti: 91, avatar: '🎯', cor: '#d35400' },
  { id: 'mbappe', nome: 'Kylian Mbappé', apelido: 'Mbappé', pais: 'França', time: 'Real Madrid', pos: 'ATA', overall: 92, penalti: 89, avatar: '⚡', cor: '#2c3e50' },
  { id: 'vini', nome: 'Vinícius Júnior', apelido: 'Vini Jr', pais: 'Brasil', time: 'Real Madrid', pos: 'ATA', overall: 91, penalti: 87, avatar: '🕺', cor: '#f1c40f' },
  { id: 'bellingham', nome: 'Jude Bellingham', apelido: 'Bellingham', pais: 'Inglaterra', time: 'Real Madrid', pos: 'MEI', overall: 90, penalti: 85, avatar: '🦁', cor: '#e67e22' },
  { id: 'kane', nome: 'Harry Kane', apelido: 'Kane', pais: 'Inglaterra', time: 'Bayern', pos: 'ATA', overall: 91, penalti: 93, avatar: '🏴', cor: '#7f8c8d' },
  { id: 'salah', nome: 'Mohamed Salah', apelido: 'Salah', pais: 'Egito', time: 'Liverpool', pos: 'ATA', overall: 90, penalti: 89, avatar: '👑', cor: '#c0392b' },
  { id: 'debruyne', nome: 'Kevin De Bruyne', apelido: 'De Bruyne', pais: 'Bélgica', time: 'Napoli', pos: 'MEI', overall: 90, penalti: 86, avatar: '🧠', cor: '#16a085' },
  { id: 'musiala', nome: 'Jamal Musiala', apelido: 'Musiala', pais: 'Alemanha', time: 'Bayern', pos: 'MEI', overall: 89, penalti: 84, avatar: '🎩', cor: '#2e86c1' },
  { id: 'valverde', nome: 'Fede Valverde', apelido: 'Valverde', pais: 'Uruguai', time: 'Real Madrid', pos: 'MEI', overall: 89, penalti: 83, avatar: '🚀', cor: '#117a65' },
  { id: 'leao', nome: 'Rafael Leão', apelido: 'Leão', pais: 'Portugal', time: 'Milan', pos: 'ATA', overall: 88, penalti: 82, avatar: '🐆', cor: '#922b21' },
  { id: 'endrick', nome: 'Endrick', apelido: 'Endrick', pais: 'Brasil', time: 'Real Madrid', pos: 'ATA', overall: 85, penalti: 82, avatar: '💎', cor: '#1abc9c' },
  { id: 'estevao', nome: 'Estêvão', apelido: 'Estêvão', pais: 'Brasil', time: 'Chelsea', pos: 'ATA', overall: 84, penalti: 81, avatar: '✨', cor: '#2471a3' },
  { id: 'grizou', nome: 'Antoine Griezmann', apelido: 'Griezmann', pais: 'França', time: 'Atlético de Madrid', pos: 'ATA', overall: 89, penalti: 87, avatar: '🎮', cor: '#b03a2e' },
];

const TIMES = [
  { id: 'real', nome: 'Real Madrid', sigla: 'RMA', tipo: 'clube', cor1: '#ffffff', cor2: '#c9a600', forca: 94, goleiro: 'Courtois (91)', craques: ['mbappe','vini','bellingham','valverde','endrick'] },
  { id: 'barca', nome: 'Barça', sigla: 'BAR', tipo: 'clube', cor1: '#004d98', cor2: '#a50044', forca: 92, goleiro: 'Ter Stegen (89)', craques: ['yamal','lewa'] },
  { id: 'atleti', nome: 'Atlético de Madrid', sigla: 'ATM', tipo: 'clube', cor1: '#cb3524', cor2: '#ffffff', forca: 88, goleiro: 'Oblak (91)', craques: ['grizou'] },
  { id: 'arsenal', nome: 'Arsenal', sigla: 'ARS', tipo: 'clube', cor1: '#ef0107', cor2: '#ffffff', forca: 90, goleiro: 'Raya (87)', craques: [] },
  { id: 'chelsea', nome: 'Chelsea', sigla: 'CHE', tipo: 'clube', cor1: '#034694', cor2: '#ffffff', forca: 87, goleiro: 'Sánchez (83)', craques: ['estevao'] },
  { id: 'juve', nome: 'Juventus', sigla: 'JUV', tipo: 'clube', cor1: '#ffffff', cor2: '#000000', forca: 86, goleiro: 'Di Gregorio (86)', craques: [] },
  { id: 'corinthians', nome: 'Corinthians', sigla: 'COR', tipo: 'clube', cor1: '#ffffff', cor2: '#000000', forca: 82, goleiro: 'Hugo Souza (84)', craques: [] },
  { id: 'palmeiras', nome: 'Palmeiras', sigla: 'PAL', tipo: 'clube', cor1: '#006437', cor2: '#ffffff', forca: 84, goleiro: 'Weverton (85)', craques: [] },
  { id: 'flamengo', nome: 'Flamengo', sigla: 'FLA', tipo: 'clube', cor1: '#d0002b', cor2: '#000000', forca: 86, goleiro: 'Rossi (85)', craques: [] },
  { id: 'vasco', nome: 'Vasco', sigla: 'VAS', tipo: 'clube', cor1: '#ffffff', cor2: '#000000', forca: 80, goleiro: 'Léo Jardim (84)', craques: [] },
  { id: 'miami', nome: 'Inter Miami', sigla: 'MIA', tipo: 'clube', cor1: '#f7b5cd', cor2: '#000000', forca: 83, goleiro: 'Ustari (78)', craques: ['messi'] },
  { id: 'brasil', nome: 'Brasil', sigla: 'BRA', tipo: 'selecao', cor1: '#009c3b', cor2: '#ffdf00', forca: 92, goleiro: 'Alisson (89)', craques: ['neymar','vini','endrick','estevao'] },
  { id: 'argentina', nome: 'Argentina', sigla: 'ARG', tipo: 'selecao', cor1: '#75aadb', cor2: '#ffffff', forca: 93, goleiro: 'E. Martínez (89)', craques: ['messi'] },
  { id: 'portugal', nome: 'Portugal', sigla: 'POR', tipo: 'selecao', cor1: '#046a38', cor2: '#da291c', forca: 91, goleiro: 'D. Costa (87)', craques: ['cr7','leao'] },
  { id: 'franca', nome: 'França', sigla: 'FRA', tipo: 'selecao', cor1: '#002395', cor2: '#ffffff', forca: 92, goleiro: 'Maignan (88)', craques: ['mbappe','grizou'] },
  { id: 'espanha', nome: 'Espanha', sigla: 'ESP', tipo: 'selecao', cor1: '#aa151b', cor2: '#f1bf00', forca: 91, goleiro: 'Unai Simón (86)', craques: ['yamal'] },
  { id: 'inglaterra', nome: 'Inglaterra', sigla: 'ENG', tipo: 'selecao', cor1: '#ffffff', cor2: '#012169', forca: 90, goleiro: 'Pickford (86)', craques: ['kane','bellingham'] },
  { id: 'alemanha', nome: 'Alemanha', sigla: 'GER', tipo: 'selecao', cor1: '#ffffff', cor2: '#000000', forca: 89, goleiro: 'Neuer (87)', craques: ['musiala','kane'] },
];
